// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htziyscagagblsostopa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eml5c2NhZ2FnYmxzb3N0b3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTM5MjUsImV4cCI6MjA3MzA2OTkyNX0.Zn9u57EEj7MZvfCuADWLdiZ46fJ__WBdiYXI1Uk32j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});