name: Deploy to Production

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

env:
  NODE_VERSION: '18.x'

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for staging
        run: npm run build
        env:
          NODE_ENV: staging
      
      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          # Add your staging deployment commands here
          # Example: docker build and push, or deploy to cloud provider
      
      - name: Run smoke tests
        run: |
          echo "🧪 Running smoke tests on staging"
          # Add smoke test commands here

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment"
          # Add your production deployment commands here
      
      - name: Notify deployment success
        run: |
          echo "✅ Production deployment completed successfully"